server:
  port: 8080
---
spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
