server:
  port: 8080
---
spring:
  profiles: default
  jpa:
    hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.driver
    url: jdbc:mysql://localhost:8080/
    username: root
    password: 1234

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
